[package]
name = 'button-wrappers'
version = '1.0.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-stdlib'

[addresses]
ButtonWrappers = "43c2e6729314914bbe7458cda2e10ff43813a8aaa1db002ffbb38938d309345c"