[package]
name = 'button-wrappers'
version = '1.0.0'
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-stdlib'

[addresses]
ButtonWrappers = "0x4d48f5c877702ba53793b116a7c37c349afbcb197725f1b4b14f4b2f76feca82"